package com.nepal.tourismguide.controller;
import com.nepal.tourismguide.entity.*;
import com.nepal.tourismguide.exception.ApiException;
import com.nepal.tourismguide.model.User;
import com.nepal.tourismguide.repository.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.*;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import java.time.LocalDate;
import java.util.*;

@RestController
@RequestMapping("/api")
public class UserResourceController {
 private final UserRepository users; private final DestinationRepository destinations; private final FavoriteRepository favorites; private final SavedFavoriteRepository savedFavorites; private final TripRepository trips; private final TripItemRepository items; private final ReviewEntityRepository reviews;
 public UserResourceController(UserRepository u,DestinationRepository d,FavoriteRepository f,SavedFavoriteRepository sf,TripRepository t,TripItemRepository i,ReviewEntityRepository r){users=u;destinations=d;favorites=f;savedFavorites=sf;trips=t;items=i;reviews=r;}
 private User user(Authentication a){return users.findByEmail(a.getName()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"User not found"));}
 private Map<String,Object> review(ReviewEntity r){Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.getId());m.put("rating",r.getRating());m.put("comment",r.getComment());m.put("user",r.getUser().getFullName());m.put("userEmail",r.getUser().getEmail());m.put("destinationId",r.getDestination().getId());m.put("createdAt",r.getCreatedAt());return m;}
 private Map<String,Object> favorite(Favorite f){Map<String,Object> m=new LinkedHashMap<>();m.put("id",f.getId());m.put("destinationId",f.getDestination().getId());m.put("destinationName",f.getDestination().getName());m.put("image",f.getDestination().getImages().isEmpty()?"":f.getDestination().getImages().get(0).getImageUrl());m.put("createdAt",f.getCreatedAt());return m;}
 private Map<String,Object> savedFavorite(SavedFavorite f){Map<String,Object> m=new LinkedHashMap<>();m.put("id",f.getId());m.put("itemType",f.getItemType());m.put("itemId",f.getItemId());m.put("itemName",f.getItemName());m.put("itemImage",f.getItemImage());m.put("createdAt",f.getCreatedAt());return m;}
 private Map<String,Object> trip(Trip t){Map<String,Object> m=new LinkedHashMap<>();m.put("id",t.getId());m.put("name",t.getName());m.put("startDate",t.getStartDate());m.put("endDate",t.getEndDate());m.put("budget",t.getBudget());m.put("travelStyle",t.getTravelStyle());m.put("items",t.getItems().stream().map(item -> {Map<String,Object> i=new LinkedHashMap<>();i.put("id",item.getId());i.put("dayNumber",item.getDayNumber());i.put("notes",item.getNotes());i.put("activities",item.getActivities());i.put("destination",Map.of("id",item.getDestination().getId(),"name",item.getDestination().getName()));return i;}).toList());return m;}
 @GetMapping("/destinations/{id}/reviews") public List<Map<String,Object>> reviews(@PathVariable Long id){return reviews.findByDestinationId(id).stream().map(this::review).toList();}
 @PostMapping("/destinations/{id}/reviews") public Map<String,Object> addReview(@PathVariable Long id,@Valid @RequestBody ReviewRequest request,Authentication auth){User u=user(auth); Destination d=destinations.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Destination not found")); if(reviews.findByUserIdAndDestinationId(u.getId(),id).isPresent()) throw new ApiException(HttpStatus.CONFLICT,"You have already reviewed this destination"); return review(reviews.save(new ReviewEntity(request.rating(),request.comment(),u,d)));}
 @PutMapping("/reviews/{id}") public Map<String,Object> updateReview(@PathVariable Long id,@Valid @RequestBody ReviewRequest request,Authentication auth){ReviewEntity r=reviews.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Review not found")); User u=user(auth); if(!r.getUser().getId().equals(u.getId())) throw new ApiException(HttpStatus.FORBIDDEN,"You can only edit your own reviews"); r.setRating(request.rating());r.setComment(request.comment());return review(reviews.save(r));}
 @DeleteMapping("/reviews/{id}") public ResponseEntity<Void> deleteReview(@PathVariable Long id,Authentication auth){ReviewEntity r=reviews.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Review not found")); User u=user(auth); if(!r.getUser().getId().equals(u.getId())) throw new ApiException(HttpStatus.FORBIDDEN,"You can only delete your own reviews"); reviews.delete(r);return ResponseEntity.noContent().build();}
 @GetMapping("/favorites") public List<Map<String,Object>> favoriteList(Authentication auth){return favorites.findByUserId(user(auth).getId()).stream().map(this::favorite).toList();}
 @PostMapping("/favorites/{destinationId}") public ResponseEntity<?> favorite(@PathVariable Long destinationId,Authentication auth){User u=user(auth);Destination d=destinations.findById(destinationId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Destination not found"));if(favorites.findByUserIdAndDestinationId(u.getId(),destinationId).isPresent())throw new ApiException(HttpStatus.CONFLICT,"Destination is already a favorite");return ResponseEntity.status(HttpStatus.CREATED).body(favorite(favorites.save(new Favorite(u,d))));}
 @DeleteMapping("/favorites/{destinationId}") public ResponseEntity<Void> unfavorite(@PathVariable Long destinationId,Authentication auth){Favorite f=favorites.findByUserIdAndDestinationId(user(auth).getId(),destinationId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Favorite not found"));favorites.delete(f);return ResponseEntity.noContent().build();}
 @GetMapping("/favorites/items") public List<Map<String,Object>> savedFavoriteList(Authentication auth){return savedFavorites.findByUserId(user(auth).getId()).stream().map(this::savedFavorite).toList();}
 @PostMapping("/favorites/items") public ResponseEntity<?> saveItem(@Valid @RequestBody SavedFavoriteRequest request,Authentication auth){User current=user(auth);String type=request.itemType().trim().toLowerCase(Locale.ROOT);if(!Set.of("experience","hotel","restaurant","trekking-route").contains(type))throw new ApiException(HttpStatus.BAD_REQUEST,"Unsupported favorite item type");if(savedFavorites.findByUserIdAndItemTypeAndItemId(current.getId(),type,request.itemId()).isPresent())throw new ApiException(HttpStatus.CONFLICT,"Item is already a favorite");return ResponseEntity.status(HttpStatus.CREATED).body(savedFavorite(savedFavorites.save(new SavedFavorite(current,type,request.itemId(),request.itemName(),request.itemImage()))));}
 @DeleteMapping("/favorites/items/{itemType}/{itemId}") public ResponseEntity<Void> removeItem(@PathVariable String itemType,@PathVariable String itemId,Authentication auth){SavedFavorite favorite=savedFavorites.findByUserIdAndItemTypeAndItemId(user(auth).getId(),itemType.toLowerCase(Locale.ROOT),itemId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Favorite not found"));savedFavorites.delete(favorite);return ResponseEntity.noContent().build();}
 @GetMapping("/trips") public List<Map<String,Object>> tripList(Authentication auth){return trips.findByUserId(user(auth).getId()).stream().map(this::trip).toList();}
 @GetMapping("/trips/{id}") public Map<String,Object> trip(@PathVariable Long id,Authentication auth){return trip(ownedTrip(id,auth));}
 @PostMapping("/trips") public Map<String,Object> createTrip(@Valid @RequestBody TripRequest request,Authentication auth){return trip(trips.save(new Trip(request.name(),request.startDate(),request.endDate(),request.budget(),request.travelStyle(),user(auth))));}
 @PutMapping("/trips/{id}") public Map<String,Object> updateTrip(@PathVariable Long id,@Valid @RequestBody TripRequest request,Authentication auth){Trip t=ownedTrip(id,auth);t.setName(request.name());t.setStartDate(request.startDate());t.setEndDate(request.endDate());t.setBudget(request.budget());t.setTravelStyle(request.travelStyle());return trip(trips.save(t));}
 @DeleteMapping("/trips/{id}") public ResponseEntity<Void> deleteTrip(@PathVariable Long id,Authentication auth){trips.delete(ownedTrip(id,auth));return ResponseEntity.noContent().build();}
 @PostMapping("/trips/{tripId}/items") public Map<String,Object> addItem(@PathVariable Long tripId,@Valid @RequestBody TripItemRequest request,Authentication auth){Trip t=ownedTrip(tripId,auth);Destination d=destinations.findById(request.destinationId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Destination not found"));TripItem item=items.save(new TripItem(t,d,request.dayNumber(),request.notes(),request.activities()));return trip(item.getTrip());}
 @PutMapping("/trip-items/{id}") public Map<String,Object> updateItem(@PathVariable Long id,@Valid @RequestBody TripItemRequest request,Authentication auth){TripItem i=items.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Trip item not found"));ownedTrip(i.getTrip().getId(),auth);i.setDayNumber(request.dayNumber());i.setNotes(request.notes());i.setActivities(request.activities());items.save(i);return trip(i.getTrip());}
 @DeleteMapping("/trip-items/{id}") public ResponseEntity<Void> deleteItem(@PathVariable Long id,Authentication auth){TripItem i=items.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Trip item not found"));ownedTrip(i.getTrip().getId(),auth);items.delete(i);return ResponseEntity.noContent().build();}
 private Trip ownedTrip(Long id,Authentication a){return trips.findByIdAndUserId(id,user(a).getId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Trip not found"));}
 public record ReviewRequest(@Min(1) @Max(5) int rating,@NotBlank @Size(max=2000) String comment){}
 public record TripRequest(@NotBlank @Size(max=180) String name,LocalDate startDate,LocalDate endDate,@Size(max=100) String budget,@Size(max=40) String travelStyle){}
 public record TripItemRequest(@Positive Long destinationId,@Min(1) int dayNumber,@Size(max=500) String notes,@Size(max=700) String activities){}
 public record SavedFavoriteRequest(@NotBlank @Size(max=40) String itemType,@NotBlank @Size(max=120) String itemId,@NotBlank @Size(max=180) String itemName,@Size(max=700) String itemImage){}
}
